require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ParkingLotsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ParkingLot. As you add validations to ParkingLot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParkingLotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all parking_lots as @parking_lots" do
      parking_lot = ParkingLot.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:parking_lots)).to eq([parking_lot])
    end
  end

  describe "GET show" do
    it "assigns the requested parking_lot as @parking_lot" do
      parking_lot = ParkingLot.create! valid_attributes
      get :show, {:id => parking_lot.to_param}, valid_session
      expect(assigns(:parking_lot)).to eq(parking_lot)
    end
  end

  describe "GET new" do
    it "assigns a new parking_lot as @parking_lot" do
      get :new, {}, valid_session
      expect(assigns(:parking_lot)).to be_a_new(ParkingLot)
    end
  end

  describe "GET edit" do
    it "assigns the requested parking_lot as @parking_lot" do
      parking_lot = ParkingLot.create! valid_attributes
      get :edit, {:id => parking_lot.to_param}, valid_session
      expect(assigns(:parking_lot)).to eq(parking_lot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ParkingLot" do
        expect {
          post :create, {:parking_lot => valid_attributes}, valid_session
        }.to change(ParkingLot, :count).by(1)
      end

      it "assigns a newly created parking_lot as @parking_lot" do
        post :create, {:parking_lot => valid_attributes}, valid_session
        expect(assigns(:parking_lot)).to be_a(ParkingLot)
        expect(assigns(:parking_lot)).to be_persisted
      end

      it "redirects to the created parking_lot" do
        post :create, {:parking_lot => valid_attributes}, valid_session
        expect(response).to redirect_to(ParkingLot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved parking_lot as @parking_lot" do
        post :create, {:parking_lot => invalid_attributes}, valid_session
        expect(assigns(:parking_lot)).to be_a_new(ParkingLot)
      end

      it "re-renders the 'new' template" do
        post :create, {:parking_lot => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parking_lot" do
        parking_lot = ParkingLot.create! valid_attributes
        put :update, {:id => parking_lot.to_param, :parking_lot => new_attributes}, valid_session
        parking_lot.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested parking_lot as @parking_lot" do
        parking_lot = ParkingLot.create! valid_attributes
        put :update, {:id => parking_lot.to_param, :parking_lot => valid_attributes}, valid_session
        expect(assigns(:parking_lot)).to eq(parking_lot)
      end

      it "redirects to the parking_lot" do
        parking_lot = ParkingLot.create! valid_attributes
        put :update, {:id => parking_lot.to_param, :parking_lot => valid_attributes}, valid_session
        expect(response).to redirect_to(parking_lot)
      end
    end

    describe "with invalid params" do
      it "assigns the parking_lot as @parking_lot" do
        parking_lot = ParkingLot.create! valid_attributes
        put :update, {:id => parking_lot.to_param, :parking_lot => invalid_attributes}, valid_session
        expect(assigns(:parking_lot)).to eq(parking_lot)
      end

      it "re-renders the 'edit' template" do
        parking_lot = ParkingLot.create! valid_attributes
        put :update, {:id => parking_lot.to_param, :parking_lot => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested parking_lot" do
      parking_lot = ParkingLot.create! valid_attributes
      expect {
        delete :destroy, {:id => parking_lot.to_param}, valid_session
      }.to change(ParkingLot, :count).by(-1)
    end

    it "redirects to the parking_lots list" do
      parking_lot = ParkingLot.create! valid_attributes
      delete :destroy, {:id => parking_lot.to_param}, valid_session
      expect(response).to redirect_to(parking_lots_url)
    end
  end

end
